
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Apr 19 17:26:50 VET 2015
//----------------------------------------------------

package compilador;

import java_cup.runtime.*;
import ast.*;
import compilador.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Sun Apr 19 17:26:50 VET 2015
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\107\000\002\002\003\000\002\002\004\000\002\003" +
    "\004\000\002\003\003\000\002\032\004\000\002\032\003" +
    "\000\002\031\010\000\002\033\006\000\002\033\004\000" +
    "\002\033\003\000\002\004\005\000\002\005\005\000\002" +
    "\005\003\000\002\006\003\000\002\006\003\000\002\006" +
    "\003\000\002\006\003\000\002\006\003\000\002\006\003" +
    "\000\002\006\003\000\002\006\003\000\002\006\003\000" +
    "\002\006\003\000\002\007\007\000\002\007\011\000\002" +
    "\010\006\000\002\041\002\000\002\011\006\000\002\036" +
    "\004\000\002\035\004\000\002\023\004\000\002\023\004" +
    "\000\002\023\004\000\002\024\003\000\002\024\003\000" +
    "\002\024\003\000\002\025\005\000\002\025\003\000\002" +
    "\026\006\000\002\027\005\000\002\027\003\000\002\027" +
    "\003\000\002\030\003\000\002\030\003\000\002\040\003" +
    "\000\002\040\003\000\002\012\005\000\002\012\003\000" +
    "\002\014\005\000\002\014\003\000\002\015\005\000\002" +
    "\015\003\000\002\016\005\000\002\016\003\000\002\017" +
    "\005\000\002\017\005\000\002\017\005\000\002\017\005" +
    "\000\002\017\003\000\002\013\005\000\002\013\005\000" +
    "\002\013\003\000\002\020\005\000\002\020\005\000\002" +
    "\020\003\000\002\021\005\000\002\021\003\000\002\021" +
    "\003\000\002\021\003\000\002\034\004\000\002\037\014" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\201\000\006\007\005\045\007\001\002\000\004\002" +
    "\203\001\002\000\030\003\046\004\041\011\053\013\034" +
    "\014\042\015\052\016\016\017\017\020\015\021\037\047" +
    "\043\001\002\000\012\007\005\016\016\017\017\020\015" +
    "\001\002\000\012\007\ufffc\016\ufffc\017\ufffc\020\ufffc\001" +
    "\002\000\004\002\ufffe\001\002\000\004\002\001\001\002" +
    "\000\012\007\ufffd\016\ufffd\017\ufffd\020\ufffd\001\002\000" +
    "\004\047\020\001\002\000\004\002\uffff\001\002\000\012" +
    "\003\uffdf\037\uffdf\046\uffdf\047\uffdf\001\002\000\012\003" +
    "\uffde\037\uffde\046\uffde\047\uffde\001\002\000\012\003\uffe0" +
    "\037\uffe0\046\uffe0\047\uffe0\001\002\000\004\037\021\001" +
    "\002\000\012\016\016\017\017\020\015\045\023\001\002" +
    "\000\004\047\032\001\002\000\006\040\ufff8\044\ufff8\001" +
    "\002\000\006\040\026\044\025\001\002\000\010\016\016" +
    "\017\017\020\015\001\002\000\004\007\005\001\002\000" +
    "\012\007\ufffb\016\ufffb\017\ufffb\020\ufffb\001\002\000\004" +
    "\047\031\001\002\000\006\040\ufffa\044\ufffa\001\002\000" +
    "\006\040\ufff9\044\ufff9\001\002\000\012\006\ufff3\010\ufff3" +
    "\012\ufff3\043\ufff3\001\002\000\004\047\202\001\002\000" +
    "\012\006\uffee\010\uffee\012\uffee\043\uffee\001\002\000\012" +
    "\003\071\037\073\046\062\047\173\001\002\000\012\003" +
    "\071\037\073\046\062\047\067\001\002\000\012\006\ufff1" +
    "\010\ufff1\012\ufff1\043\ufff1\001\002\000\012\003\071\037" +
    "\073\046\062\047\067\001\002\000\012\003\071\037\073" +
    "\046\062\047\067\001\002\000\006\022\uffe7\037\147\001" +
    "\002\000\012\006\uffed\010\uffed\012\uffed\043\uffed\001\002" +
    "\000\006\010\146\043\060\001\002\000\012\006\uffeb\010" +
    "\uffeb\012\uffeb\043\uffeb\001\002\000\012\006\ufff4\010\ufff4" +
    "\012\ufff4\043\ufff4\001\002\000\012\006\uffec\010\uffec\012" +
    "\uffec\043\uffec\001\002\000\012\006\ufff0\010\ufff0\012\ufff0" +
    "\043\ufff0\001\002\000\004\037\131\001\002\000\030\003" +
    "\046\004\041\011\053\013\034\014\042\015\052\016\016" +
    "\017\017\020\015\021\037\047\043\001\002\000\012\006" +
    "\uffef\010\uffef\012\uffef\043\uffef\001\002\000\012\006\ufff5" +
    "\010\ufff5\012\ufff5\043\ufff5\001\002\000\012\006\ufff2\010" +
    "\ufff2\012\ufff2\043\ufff2\001\002\000\006\012\061\043\060" +
    "\001\002\000\030\003\046\004\041\011\053\013\034\014" +
    "\042\015\052\016\016\017\017\020\015\021\037\047\043" +
    "\001\002\000\012\003\071\037\073\046\062\047\067\001" +
    "\002\000\050\005\uffbf\006\uffbf\010\uffbf\012\uffbf\022\uffbf" +
    "\023\uffbf\024\uffbf\025\uffbf\026\uffbf\027\uffbf\030\uffbf\031" +
    "\uffbf\032\uffbf\033\uffbf\035\uffbf\036\uffbf\040\uffbf\043\uffbf" +
    "\044\uffbf\001\002\000\026\005\uffd0\006\uffd0\010\uffd0\012" +
    "\uffd0\023\106\035\uffd0\036\uffd0\040\uffd0\043\uffd0\044\uffd0" +
    "\001\002\000\024\005\uffd2\006\uffd2\010\uffd2\012\uffd2\035" +
    "\104\036\uffd2\040\uffd2\043\uffd2\044\uffd2\001\002\000\050" +
    "\005\uffc4\006\uffc4\010\uffc4\012\uffc4\022\uffc4\023\uffc4\024" +
    "\uffc4\025\uffc4\026\uffc4\027\uffc4\030\uffc4\031\uffc4\032\120" +
    "\033\117\035\uffc4\036\uffc4\040\uffc4\043\uffc4\044\uffc4\001" +
    "\002\000\014\006\uffe8\010\uffe8\012\uffe8\036\102\043\uffe8" +
    "\001\002\000\050\005\uffbe\006\uffbe\010\uffbe\012\uffbe\022" +
    "\uffbe\023\uffbe\024\uffbe\025\uffbe\026\uffbe\027\uffbe\030\uffbe" +
    "\031\uffbe\032\uffbe\033\uffbe\035\uffbe\036\uffbe\040\uffbe\043" +
    "\uffbe\044\uffbe\001\002\000\050\005\uffc1\006\uffc1\010\uffc1" +
    "\012\uffc1\022\uffc1\023\uffc1\024\uffc1\025\uffc1\026\uffc1\027" +
    "\uffc1\030\uffc1\031\uffc1\032\uffc1\033\uffc1\035\uffc1\036\uffc1" +
    "\040\uffc1\043\uffc1\044\uffc1\001\002\000\050\005\uffbd\006" +
    "\uffbd\010\uffbd\012\uffbd\022\uffbd\023\uffbd\024\uffbd\025\uffbd" +
    "\026\uffbd\027\uffbd\030\uffbd\031\uffbd\032\uffbd\033\uffbd\035" +
    "\uffbd\036\uffbd\040\uffbd\043\uffbd\044\uffbd\001\002\000\044" +
    "\005\uffc7\006\uffc7\010\uffc7\012\uffc7\022\uffc7\023\uffc7\024" +
    "\110\025\111\026\113\027\114\030\112\031\115\035\uffc7" +
    "\036\uffc7\040\uffc7\043\uffc7\044\uffc7\001\002\000\012\003" +
    "\071\037\073\046\062\047\067\001\002\000\030\005\uffcc" +
    "\006\uffcc\010\uffcc\012\uffcc\022\uffcc\023\uffcc\035\uffcc\036" +
    "\uffcc\040\uffcc\043\uffcc\044\uffcc\001\002\000\030\005\uffce" +
    "\006\uffce\010\uffce\012\uffce\022\076\023\uffce\035\uffce\036" +
    "\uffce\040\uffce\043\uffce\044\uffce\001\002\000\012\003\071" +
    "\037\073\046\062\047\067\001\002\000\030\005\uffcd\006" +
    "\uffcd\010\uffcd\012\uffcd\022\uffcd\023\uffcd\035\uffcd\036\uffcd" +
    "\040\uffcd\043\uffcd\044\uffcd\001\002\000\006\036\102\040" +
    "\101\001\002\000\050\005\uffc0\006\uffc0\010\uffc0\012\uffc0" +
    "\022\uffc0\023\uffc0\024\uffc0\025\uffc0\026\uffc0\027\uffc0\030" +
    "\uffc0\031\uffc0\032\uffc0\033\uffc0\035\uffc0\036\uffc0\040\uffc0" +
    "\043\uffc0\044\uffc0\001\002\000\012\003\071\037\073\046" +
    "\062\047\067\001\002\000\024\005\uffd3\006\uffd3\010\uffd3" +
    "\012\uffd3\035\104\036\uffd3\040\uffd3\043\uffd3\044\uffd3\001" +
    "\002\000\012\003\071\037\073\046\062\047\067\001\002" +
    "\000\026\005\uffd1\006\uffd1\010\uffd1\012\uffd1\023\106\035" +
    "\uffd1\036\uffd1\040\uffd1\043\uffd1\044\uffd1\001\002\000\012" +
    "\003\071\037\073\046\062\047\067\001\002\000\030\005" +
    "\uffcf\006\uffcf\010\uffcf\012\uffcf\022\076\023\uffcf\035\uffcf" +
    "\036\uffcf\040\uffcf\043\uffcf\044\uffcf\001\002\000\012\003" +
    "\071\037\073\046\062\047\067\001\002\000\012\003\071" +
    "\037\073\046\062\047\067\001\002\000\012\003\071\037" +
    "\073\046\062\047\067\001\002\000\012\003\071\037\073" +
    "\046\062\047\067\001\002\000\012\003\071\037\073\046" +
    "\062\047\067\001\002\000\012\003\071\037\073\046\062" +
    "\047\067\001\002\000\050\005\uffc5\006\uffc5\010\uffc5\012" +
    "\uffc5\022\uffc5\023\uffc5\024\uffc5\025\uffc5\026\uffc5\027\uffc5" +
    "\030\uffc5\031\uffc5\032\120\033\117\035\uffc5\036\uffc5\040" +
    "\uffc5\043\uffc5\044\uffc5\001\002\000\012\003\071\037\073" +
    "\046\062\047\067\001\002\000\012\003\071\037\073\046" +
    "\062\047\067\001\002\000\050\005\uffc3\006\uffc3\010\uffc3" +
    "\012\uffc3\022\uffc3\023\uffc3\024\uffc3\025\uffc3\026\uffc3\027" +
    "\uffc3\030\uffc3\031\uffc3\032\uffc3\033\uffc3\035\uffc3\036\uffc3" +
    "\040\uffc3\043\uffc3\044\uffc3\001\002\000\050\005\uffc2\006" +
    "\uffc2\010\uffc2\012\uffc2\022\uffc2\023\uffc2\024\uffc2\025\uffc2" +
    "\026\uffc2\027\uffc2\030\uffc2\031\uffc2\032\uffc2\033\uffc2\035" +
    "\uffc2\036\uffc2\040\uffc2\043\uffc2\044\uffc2\001\002\000\034" +
    "\005\uffc8\006\uffc8\010\uffc8\012\uffc8\022\uffc8\023\uffc8\030" +
    "\112\031\115\035\uffc8\036\uffc8\040\uffc8\043\uffc8\044\uffc8" +
    "\001\002\000\034\005\uffc9\006\uffc9\010\uffc9\012\uffc9\022" +
    "\uffc9\023\uffc9\030\112\031\115\035\uffc9\036\uffc9\040\uffc9" +
    "\043\uffc9\044\uffc9\001\002\000\050\005\uffc6\006\uffc6\010" +
    "\uffc6\012\uffc6\022\uffc6\023\uffc6\024\uffc6\025\uffc6\026\uffc6" +
    "\027\uffc6\030\uffc6\031\uffc6\032\120\033\117\035\uffc6\036" +
    "\uffc6\040\uffc6\043\uffc6\044\uffc6\001\002\000\034\005\uffca" +
    "\006\uffca\010\uffca\012\uffca\022\uffca\023\uffca\030\112\031" +
    "\115\035\uffca\036\uffca\040\uffca\043\uffca\044\uffca\001\002" +
    "\000\034\005\uffcb\006\uffcb\010\uffcb\012\uffcb\022\uffcb\023" +
    "\uffcb\030\112\031\115\035\uffcb\036\uffcb\040\uffcb\043\uffcb" +
    "\044\uffcb\001\002\000\012\006\ufff6\010\ufff6\012\ufff6\043" +
    "\ufff6\001\002\000\004\047\132\001\002\000\004\022\uffe7" +
    "\001\002\000\004\043\134\001\002\000\012\003\071\037" +
    "\073\046\062\047\067\001\002\000\006\036\102\043\136" +
    "\001\002\000\004\047\132\001\002\000\004\040\140\001" +
    "\002\000\030\003\046\004\041\011\053\013\034\014\042" +
    "\015\052\016\016\017\017\020\015\021\037\047\043\001" +
    "\002\000\006\010\142\043\060\001\002\000\012\006\uffbb" +
    "\010\uffbb\012\uffbb\043\uffbb\001\002\000\004\022\144\001" +
    "\002\000\012\003\071\037\073\046\062\047\067\001\002" +
    "\000\016\006\uffe6\010\uffe6\012\uffe6\036\102\040\uffe6\043" +
    "\uffe6\001\002\000\014\002\ufff7\007\ufff7\016\ufff7\017\ufff7" +
    "\020\ufff7\001\002\000\020\003\071\037\073\045\156\046" +
    "\062\047\067\050\152\051\154\001\002\000\006\040\uffd9" +
    "\044\uffd9\001\002\000\010\036\102\040\uffd6\044\uffd6\001" +
    "\002\000\006\040\uffd5\044\uffd5\001\002\000\006\040\uffd7" +
    "\044\uffd7\001\002\000\006\040\uffd4\044\uffd4\001\002\000" +
    "\006\040\160\044\157\001\002\000\006\040\uffd8\044\uffd8" +
    "\001\002\000\016\003\071\037\073\046\062\047\067\050" +
    "\152\051\154\001\002\000\012\006\uffdb\010\uffdb\012\uffdb" +
    "\043\uffdb\001\002\000\006\040\uffda\044\uffda\001\002\000" +
    "\014\006\uffe4\010\uffe4\012\uffe4\036\102\043\uffe4\001\002" +
    "\000\006\005\164\036\102\001\002\000\030\003\046\004" +
    "\041\011\053\013\034\014\042\015\052\016\016\017\017" +
    "\020\015\021\037\047\043\001\002\000\010\006\166\010" +
    "\167\043\060\001\002\000\030\003\046\004\041\011\053" +
    "\013\034\014\042\015\052\016\016\017\017\020\015\021" +
    "\037\047\043\001\002\000\012\006\uffea\010\uffea\012\uffea" +
    "\043\uffea\001\002\000\006\010\171\043\060\001\002\000" +
    "\012\006\uffe9\010\uffe9\012\uffe9\043\uffe9\001\002\000\014" +
    "\006\uffbc\010\uffbc\012\uffbc\036\102\043\uffbc\001\002\000" +
    "\016\006\uffbe\010\uffbe\012\uffbe\022\uffe7\043\uffbe\044\uffbe" +
    "\001\002\000\012\006\uffe1\010\uffe1\012\uffe1\043\uffe1\001" +
    "\002\000\014\006\uffe3\010\uffe3\012\uffe3\043\uffe3\044\200" +
    "\001\002\000\012\006\uffe2\010\uffe2\012\uffe2\043\uffe2\001" +
    "\002\000\014\006\uffdc\010\uffdc\012\uffdc\043\uffdc\044\uffdc" +
    "\001\002\000\012\003\071\037\073\046\062\047\067\001" +
    "\002\000\014\006\uffdd\010\uffdd\012\uffdd\043\uffdd\044\uffdd" +
    "\001\002\000\012\006\uffe5\010\uffe5\012\uffe5\043\uffe5\001" +
    "\002\000\004\002\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\201\000\012\002\003\003\010\004\007\032\005\001" +
    "\001\000\002\001\001\000\032\005\044\006\054\007\046" +
    "\010\032\011\055\023\053\024\035\026\034\034\043\035" +
    "\050\036\037\037\047\001\001\000\010\004\013\024\012" +
    "\031\011\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\024\021\033\023\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\024\027\001\001\000\004\004\026\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\012\011\175\021\176\022\173\025\174\001\001\000" +
    "\022\012\171\013\071\014\063\015\062\016\074\017\073" +
    "\020\064\021\067\001\001\000\002\001\001\000\022\012" +
    "\162\013\071\014\063\015\062\016\074\017\073\020\064" +
    "\021\067\001\001\000\022\012\161\013\071\014\063\015" +
    "\062\016\074\017\073\020\064\021\067\001\001\000\004" +
    "\041\142\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\032\005\056\006\054\007" +
    "\046\010\032\011\055\023\053\024\035\026\034\034\043" +
    "\035\050\036\037\037\047\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\030" +
    "\006\127\007\046\010\032\011\055\023\053\024\035\026" +
    "\034\034\043\035\050\036\037\037\047\001\001\000\022" +
    "\012\065\013\071\014\063\015\062\016\074\017\073\020" +
    "\064\021\067\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\022\012\077\013\071\014\063\015\062\016" +
    "\074\017\073\020\064\021\067\001\001\000\002\001\001" +
    "\000\002\001\001\000\012\013\071\017\076\020\064\021" +
    "\067\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\020\013\071\014\102\015\062\016\074\017" +
    "\073\020\064\021\067\001\001\000\002\001\001\000\016" +
    "\013\071\015\104\016\074\017\073\020\064\021\067\001" +
    "\001\000\002\001\001\000\014\013\071\016\106\017\073" +
    "\020\064\021\067\001\001\000\002\001\001\000\010\013" +
    "\126\020\064\021\067\001\001\000\010\013\125\020\064" +
    "\021\067\001\001\000\006\020\124\021\067\001\001\000" +
    "\010\013\123\020\064\021\067\001\001\000\010\013\122" +
    "\020\064\021\067\001\001\000\006\020\115\021\067\001" +
    "\001\000\002\001\001\000\004\021\121\001\001\000\004" +
    "\021\120\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\011" +
    "\132\001\001\000\004\041\142\001\001\000\002\001\001" +
    "\000\022\012\134\013\071\014\063\015\062\016\074\017" +
    "\073\020\064\021\067\001\001\000\002\001\001\000\004" +
    "\011\136\001\001\000\002\001\001\000\032\005\140\006" +
    "\054\007\046\010\032\011\055\023\053\024\035\026\034" +
    "\034\043\035\050\036\037\037\047\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\022\012\144" +
    "\013\071\014\063\015\062\016\074\017\073\020\064\021" +
    "\067\001\001\000\002\001\001\000\002\001\001\000\030" +
    "\012\150\013\071\014\063\015\062\016\074\017\073\020" +
    "\064\021\067\027\154\030\147\040\152\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\026\012\150\013\071\014\063\015\062\016\074\017" +
    "\073\020\064\021\067\030\160\040\152\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\032\005\164\006\054\007\046\010\032\011\055" +
    "\023\053\024\035\026\034\034\043\035\050\036\037\037" +
    "\047\001\001\000\002\001\001\000\032\005\167\006\054" +
    "\007\046\010\032\011\055\023\053\024\035\026\034\034" +
    "\043\035\050\036\037\037\047\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\041\142\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\021\200\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {


	private boolean modoDepuracion=true;
	private NodoBase ast=null;
	private int lineanum=0;
	
	//Debe ser llamada solo despues de un parse(), en caso contrario retornara null siempre;
	public NodoBase getASTroot(){
		return ast;
	}

  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // for_stmt ::= FOR LPAREN assign_stmt SEMI exp SEMI assign_stmt RPAREN stmt_seq END 
            {
              NodoBase RESULT =null;
		int asigleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).left;
		int asigright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).right;
		NodoBase asig = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-7)).value;
		int expressleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int expressright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		NodoBase express = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int asignaleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int asignaright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		NodoBase asigna = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int sentleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int sentright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		NodoBase sent = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 System.out.println("\t Entró a for_stmt --> FOR LPAREN assign_stmt SEMI exp assign_stmt RPAREN stmt_seq END");   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("for_stmt",29, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // return_stmt ::= RETURN exp 
            {
              NodoBase RESULT =null;
		int expresleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int expresright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase expres = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 System.out.println("\t Entró a return_stmt --> RETURN exp");   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("return_stmt",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // factor ::= error 
            {
              NodoBase RESULT =null;
		 if(modoDepuracion) System.out.println("\t Entro a factor --> error"); 
				System.out.println("Ocurrio error en cup # 0003");
				RESULT=null;
				
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // factor ::= ID 
            {
              NodoBase RESULT =null;
		int variableleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int variableright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object variable = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(modoDepuracion) System.out.println("\t Entro a factor --> ID"); 
					if(variable!=null){
						System.out.println("Construyendo Nodo ID para Lexema: "+ variable.toString());
						RESULT= new NodoIdentificador(variable.toString());		
					}else{
						RESULT = null;
						System.out.println("Ocurrio error en cup # 0005");
					}
					
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // factor ::= NUM 
            {
              NodoBase RESULT =null;
		int valorleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int valorright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Integer valor = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(modoDepuracion) System.out.println("\t Entro a factor --> NUM"); 
					System.out.println("Devolvi nodo numero entero");
					if(valor!=null){
						RESULT= new NodoValor(valor);					
					}else{
						RESULT = null;
						System.out.println("Ocurrio error en cup # 0005");
					}
					
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // factor ::= LPAREN exp RPAREN 
            {
              NodoBase RESULT =null;
		int exleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int exright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		NodoBase ex = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 if(modoDepuracion) System.out.println("\t Entro a factor --> LPAREN exp RPAREN"); 
							RESULT = ex;
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // term ::= factor 
            {
              NodoBase RESULT =null;
		int exleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int exright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase ex = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(modoDepuracion) System.out.println("\t Entro a term --> factor"); 
					RESULT=ex;
					
              CUP$parser$result = parser.getSymbolFactory().newSymbol("term",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // term ::= term OVER factor 
            {
              NodoBase RESULT =null;
		int exIleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int exIright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		NodoBase exI = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int exDleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int exDright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase exD = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(modoDepuracion) System.out.println("\t Entro a term --> term OVER factor"); 
						RESULT = new NodoOperacion(exI,tipoOp.entre,exD);
						
              CUP$parser$result = parser.getSymbolFactory().newSymbol("term",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // term ::= term TIMES factor 
            {
              NodoBase RESULT =null;
		int exIleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int exIright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		NodoBase exI = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int exDleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int exDright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase exD = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(modoDepuracion) System.out.println("\t Entro a term --> term TIMES factor"); 
							RESULT = new NodoOperacion(exI,tipoOp.por,exD);
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("term",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // simple_exp ::= term 
            {
              NodoBase RESULT =null;
		int exleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int exright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase ex = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(modoDepuracion) System.out.println("\t Entro a simple_exp --> term"); 
				RESULT=ex;
				
              CUP$parser$result = parser.getSymbolFactory().newSymbol("simple_exp",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // simple_exp ::= simple_exp MINUS term 
            {
              NodoBase RESULT =null;
		int exIleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int exIright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		NodoBase exI = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int exDleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int exDright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase exD = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(modoDepuracion) System.out.println("\t Entro a simple_exp --> simple_exp MINUS simple_exp"); 
							RESULT = new NodoOperacion(exI,tipoOp.menos,exD);
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("simple_exp",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // simple_exp ::= simple_exp PLUS term 
            {
              NodoBase RESULT =null;
		int exIleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int exIright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		NodoBase exI = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int exDleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int exDright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase exD = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(modoDepuracion) System.out.println("\t Entro a simple_exp --> simple_exp PLUS simple_exp"); 
							RESULT = new NodoOperacion(exI,tipoOp.mas,exD);
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("simple_exp",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // simple_exp4 ::= simple_exp 
            {
              NodoBase RESULT =null;
		int exleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int exright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase ex = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(modoDepuracion) System.out.println("\t regla 9c"); 
					RESULT = ex;
					
              CUP$parser$result = parser.getSymbolFactory().newSymbol("simple_exp4",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // simple_exp4 ::= simple_exp GE simple_exp 
            {
              NodoBase RESULT =null;
		int exIzleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int exIzright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		NodoBase exIz = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int exDeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int exDeright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase exDe = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(modoDepuracion) System.out.println("\t regla 9a"); 
								RESULT = new NodoOperacion(exIz,tipoOp.mayorIg,exDe);
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("simple_exp4",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // simple_exp4 ::= simple_exp LE simple_exp 
            {
              NodoBase RESULT =null;
		int exIzleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int exIzright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		NodoBase exIz = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int exDeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int exDeright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase exDe = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(modoDepuracion) System.out.println("\t regla 9a"); 
								RESULT = new NodoOperacion(exIz,tipoOp.menorIg,exDe);
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("simple_exp4",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // simple_exp4 ::= simple_exp GT simple_exp 
            {
              NodoBase RESULT =null;
		int exIzleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int exIzright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		NodoBase exIz = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int exDeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int exDeright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase exDe = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(modoDepuracion) System.out.println("\t regla 9a"); 
								RESULT = new NodoOperacion(exIz,tipoOp.mayor,exDe);
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("simple_exp4",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // simple_exp4 ::= simple_exp LT simple_exp 
            {
              NodoBase RESULT =null;
		int exIleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int exIright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		NodoBase exI = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int exDleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int exDright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase exD = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(modoDepuracion) System.out.println("\t regla 9a"); 
								RESULT = new NodoOperacion(exI,tipoOp.menor,exD);
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("simple_exp4",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // simple_exp3 ::= simple_exp4 
            {
              NodoBase RESULT =null;
		int exculeft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int excuright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase excu = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = excu; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("simple_exp3",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // simple_exp3 ::= simple_exp3 ASSIGN simple_exp4 
            {
              NodoBase RESULT =null;
		int etresleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int etresright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		NodoBase etres = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int eculeft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int ecuright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase ecu = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
              RESULT = new NodoExpresion(etres, ecu); 
             
             
              CUP$parser$result = parser.getSymbolFactory().newSymbol("simple_exp3",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // simple_exp2 ::= simple_exp3 
            {
              NodoBase RESULT =null;
		int etrleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int etrright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase etr = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT= etr; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("simple_exp2",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // simple_exp2 ::= simple_exp2 EQ simple_exp3 
            {
              NodoBase RESULT =null;
		int exIleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int exIright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		NodoBase exI = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int exDleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int exDright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase exD = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(modoDepuracion) System.out.println("\t regla 9b"); 
							RESULT = new NodoOperacion(exI,tipoOp.igual,exD); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("simple_exp2",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // simple_exp1 ::= simple_exp2 
            {
              NodoBase RESULT =null;
		int exDleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int exDright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase exD = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT= exD; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("simple_exp1",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // simple_exp1 ::= simple_exp1 AND simple_exp2 
            {
              NodoBase RESULT =null;
		int exIzleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int exIzright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		NodoBase exIz = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int exDoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int exDoright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase exDo = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
RESULT = new NodoExpresion(exIz, exDo); 
             
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("simple_exp1",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // exp ::= simple_exp1 
            {
              NodoBase RESULT =null;
		int eunoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eunoright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase euno = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = euno; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // exp ::= exp OR simple_exp1 
            {
              NodoBase RESULT =null;
		int exIzleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int exIzright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		NodoBase exIz = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int exDrleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int exDrright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase exDr = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                  RESULT = new NodoExpresion(exIz, exDr); 
              
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // bool ::= FALSE 
            {
              NodoBase RESULT =null;
		 System.out.println("\t Entró abool--> FALSE"); RESULT= new NodoBool(false); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool",30, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // bool ::= TRUE 
            {
              NodoBase RESULT =null;
		 System.out.println("\t Entró abool--> TRUE"); RESULT= new NodoBool(true); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool",30, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // param ::= exp 
            {
              NodoBase RESULT =null;
		int expresleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int expresright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase expres = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 System.out.println("\t Entró a param --> exp");  RESULT =expres; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("param",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // param ::= bool 
            {
              NodoBase RESULT =null;
		int booleanoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int booleanoright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase booleano = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 System.out.println("\t Entró a param --> bool"); RESULT=booleano;   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("param",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // param_list ::= EMPTY 
            {
              NodoBase RESULT =null;
		 System.out.println("\t Entró a param_list --> EMPTY");   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("param_list",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // param_list ::= param 
            {
              NodoBase RESULT =null;
		int parametroleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int parametroright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase parametro = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 System.out.println("\t Entró a param_list --> param");  RESULT= parametro; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("param_list",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // param_list ::= param_list COMMA param 
            {
              NodoBase RESULT =null;
		int listaleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int listaright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		NodoBase lista = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int parametroleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int parametroright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase parametro = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 System.out.println("\t Entró a param_list --> param_list COMMA param");
  
          NodoBase hijoActual = lista;
						if(hijoActual !=null){
							while(hijoActual.TieneHermano()){
								hijoActual = hijoActual.getHermanoDerecha();
							}
							hijoActual.setHermanoDerecha(parametro);
							RESULT=lista;
						}else{
							RESULT=parametro;
						}
  
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("param_list",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // call_funct ::= ID LPAREN param_list RPAREN 
            {
              NodoBase RESULT =null;
		int identleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int identright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Object ident = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int plistleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int plistright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		NodoBase plist = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 System.out.println("\t Entró a call_funct --> ID LPAREN param_list RPAREN"); 
RESULT = new NodoCall(ident.toString(), plist);

       
              CUP$parser$result = parser.getSymbolFactory().newSymbol("call_funct",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // var_list ::= factor 
            {
              NodoBase RESULT =null;
		int varleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int varright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase var = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 System.out.println("\t Entró a var_list --> factor"); RESULT= var;  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("var_list",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // var_list ::= var_list COMMA factor 
            {
              NodoBase RESULT =null;
		int listaleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int listaright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		NodoBase lista = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int varleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int varright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase var = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 System.out.println("\t Entro a var_list --> var_list COMMA factor"); 
                        NodoBase hijoActual = lista;
						if(hijoActual !=null){
							while(hijoActual.TieneHermano()){
								hijoActual = hijoActual.getHermanoDerecha();
							}
							hijoActual.setHermanoDerecha(var);
							RESULT=lista;
						}else{
							RESULT=var;
						}

 
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("var_list",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // type ::= VOID 
            {
              NodoBase RESULT =null;
		 System.out.println("\t Entró a type --> VOID"); RESULT= new NodoType("VOID");  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("type",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // type ::= BOOLEAN 
            {
              NodoBase RESULT =null;
		 System.out.println("\t Entró a type --> BOOLEAN"); RESULT= new NodoType("BOOLEAN"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("type",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // type ::= INT 
            {
              NodoBase RESULT =null;
		 System.out.println("\t Entró a type --> INT"); RESULT= new NodoType("INT");   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("type",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // decl_stmt ::= type vector 
            {
              NodoBase RESULT =null;
		int tipoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int tiporight = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		NodoBase tipo = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int vecleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vecright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase vec = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 System.out.println("\t Entró a Entró a decl_stmt --> type vector"); 
			      RESULT = new NodoAsignacion(tipo.toString(), vec);
			         
			
              CUP$parser$result = parser.getSymbolFactory().newSymbol("decl_stmt",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // decl_stmt ::= type assign_stmt 
            {
              NodoBase RESULT =null;
		int tipoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int tiporight = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		NodoBase tipo = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int astmtleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int astmtright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase astmt = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 System.out.println("\t Entró a decl_stmt --> type assign_stmt"); 
                      RESULT = new NodoAsignacion(tipo.toString(), astmt);
			    
			
              CUP$parser$result = parser.getSymbolFactory().newSymbol("decl_stmt",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // decl_stmt ::= type var_list 
            {
              NodoBase RESULT =null;
		int tipoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int tiporight = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		NodoBase tipo = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int listaleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listaright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase lista = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 System.out.println("\t Entró a decl_stmt --> type val_list"); 
                       RESULT = new NodoDecla(tipo.toString(), lista); 

            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("decl_stmt",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // write_stmt ::= WRITE exp 
            {
              NodoBase RESULT =null;
		int exleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int exright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase ex = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(modoDepuracion) System.out.println("\t Entro a write_stmt --> WRITE ID"); 
					RESULT= new NodoEscribir(ex);
					
              CUP$parser$result = parser.getSymbolFactory().newSymbol("write_stmt",27, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // read_stmt ::= READ ID 
            {
              NodoBase RESULT =null;
		int variableleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int variableright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object variable = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(modoDepuracion) System.out.println("\t Entro a read_stmt --> READ ID"); 
					System.out.println("Leyendo Variable");
					if(variable!=null)
					RESULT = new NodoLeer(variable.toString());
					else{
					RESULT = null;
					System.out.println("Ocurrio error en cup # 0002");
					}
					
              CUP$parser$result = parser.getSymbolFactory().newSymbol("read_stmt",28, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // assign_stmt ::= ID NT$0 ASSIGN exp 
            {
              NodoBase RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (NodoBase) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int variableleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int variableright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Object variable = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int exleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int exright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase ex = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(modoDepuracion) System.out.println("\t regla 6 parte final");
					if(variable!=null)
					RESULT = new NodoAsignacion(variable.toString(),ex);
					else{
					RESULT = null;
					System.out.println("Ocurrio error en cup # 0001");
					}
					
              CUP$parser$result = parser.getSymbolFactory().newSymbol("assign_stmt",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // NT$0 ::= 
            {
              NodoBase RESULT =null;
		int variableleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int variableright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object variable = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
 if(modoDepuracion) System.out.println("\t regla 6 parte del medio"); 
				/*lineanum=1000; //Pasar/Obtener la linea correcta por el Simbolo
				String nombre = variable.getName();*/
				
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$0",31, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // repeat_stmt ::= REPEAT stmt_seq UNTIL exp 
            {
              NodoBase RESULT =null;
		int cuerpoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int cuerporight = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		NodoBase cuerpo = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int pruebaleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int pruebaright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase prueba = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(modoDepuracion) System.out.println("\t Entro a repeat_stmt --> REPEAT stmt_seq UNTIL exp"); 
							RESULT = new NodoRepeat(cuerpo,prueba);
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("repeat_stmt",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // if_stmt ::= IF exp THEN stmt_seq ELSE stmt_seq END 
            {
              NodoBase RESULT =null;
		int exleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int exright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		NodoBase ex = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int pthenleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int pthenright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		NodoBase pthen = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int pelseleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int pelseright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		NodoBase pelse = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 if(modoDepuracion) System.out.println("\t Entro a if_stmt --> IF exp THEN stmt_seq ELSE stmt_seq END"); 
		RESULT = new NodoIf(ex,pthen,pelse);		
		
              CUP$parser$result = parser.getSymbolFactory().newSymbol("if_stmt",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // if_stmt ::= IF exp THEN stmt_seq END 
            {
              NodoBase RESULT =null;
		int exleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int exright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		NodoBase ex = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int pthenleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int pthenright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		NodoBase pthen = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 if(modoDepuracion) System.out.println("\t Entro a if_stmt --> IF exp THEN stmt_seq END"); 
		RESULT = new NodoIf(ex,pthen);
		
              CUP$parser$result = parser.getSymbolFactory().newSymbol("if_stmt",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // stmt ::= error 
            {
              NodoBase RESULT =null;
		 if(modoDepuracion) System.out.println("\t Entro a stmt --> error"); 
				System.out.println("Ocurrio error en stmt cup # 0004");
				RESULT=null;
				
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // stmt ::= for_stmt 
            {
              NodoBase RESULT =null;
		int varleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int varright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase var = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 System.out.println("\t Entro a stmt --> for_stmt"); RESULT=var;  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // stmt ::= return_stmt 
            {
              NodoBase RESULT =null;
		int varleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int varright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase var = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 System.out.println("\t Entro a stmt --> return_stmt"); RESULT=var;   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // stmt ::= call_funct 
            {
              NodoBase RESULT =null;
		int varleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int varright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase var = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 System.out.println("\t Entro a stmt --> call_funct"); RESULT=var;   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // stmt ::= decl_stmt 
            {
              NodoBase RESULT =null;
		int varleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int varright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase var = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 System.out.println("\t Entro a stmt --> decl_stmt");  RESULT=var;  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // stmt ::= write_stmt 
            {
              NodoBase RESULT =null;
		int sescleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sescright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase sesc = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(modoDepuracion) System.out.println("\t Entro a stmt --> write_stmt"); 
					RESULT=sesc;
					
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // stmt ::= read_stmt 
            {
              NodoBase RESULT =null;
		int slecleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int slecright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase slec = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(modoDepuracion) System.out.println("\t Entro a stmt --> read_stmt"); 
					RESULT=slec;
					
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // stmt ::= assign_stmt 
            {
              NodoBase RESULT =null;
		int sasileft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sasiright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase sasi = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(modoDepuracion) System.out.println("\t Entro a stmt --> assign_stmt"); 
						RESULT=sasi;
						
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // stmt ::= repeat_stmt 
            {
              NodoBase RESULT =null;
		int srepleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int srepright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase srep = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(modoDepuracion) System.out.println("\t Entro a stmt --> repeat_stmt"); 
						RESULT=srep;
						
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // stmt ::= if_stmt 
            {
              NodoBase RESULT =null;
		int sifleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sifright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase sif = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(modoDepuracion) System.out.println("\t Entro a stmt --> if_stmt"); 
					RESULT=sif;
					
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // stmt_seq ::= stmt 
            {
              NodoBase RESULT =null;
		int sentleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sentright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase sent = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(modoDepuracion) System.out.println("\t entro a stmt_seq --> stmt"); 
				RESULT=sent;				
				
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt_seq",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // stmt_seq ::= stmt_seq SEMI stmt 
            {
              NodoBase RESULT =null;
		int inileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int iniright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		NodoBase ini = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int sentleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sentright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase sent = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(modoDepuracion) System.out.println("\t entro a stmt_seq --> stmt_seq SEMI stmt"); 
						NodoBase hijoActual = ini;
						if(hijoActual !=null){
							while(hijoActual.TieneHermano()){
								hijoActual = hijoActual.getHermanoDerecha();
							}
							hijoActual.setHermanoDerecha(sent);
							RESULT=ini;
						}else{
							RESULT=sent;
						}
						
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt_seq",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // mainbody ::= BEGIN stmt_seq END 
            {
              NodoBase RESULT =null;
		int seculeft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int securight = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		NodoBase secu = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 System.out.println("\t Entró a mainbody --> BEGIN stmt_seq END");
                RESULT =secu;
              
              CUP$parser$result = parser.getSymbolFactory().newSymbol("mainbody",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // defpar_list ::= EMPTY 
            {
              NodoBase RESULT =null;
		 System.out.println("\t Entró a defpar_list --> EMPTY");   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("defpar_list",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // defpar_list ::= type ID 
            {
              NodoBase RESULT =null;
		int tipoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int tiporight = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		NodoBase tipo = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int identleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int identright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object ident = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 System.out.println("\t Entró a defpar_list --> type ID");  
			  RESULT=new Nodolistparam(tipo.toString(), ident.toString()); 
			 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("defpar_list",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // defpar_list ::= defpar_list COMMA type ID 
            {
              NodoBase RESULT =null;
		int listpleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int listpright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		NodoBase listp = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int tipoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int tiporight = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		NodoBase tipo = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int identleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int identright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object ident = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 System.out.println("\t Entró a defpar_list --> defpar_list COMMA type ID");
   NodoBase hijoActual= listp;
            if(hijoActual !=null){
							while(hijoActual.TieneHermano()){
								hijoActual = hijoActual.getHermanoDerecha();
							}
							hijoActual.setHermanoDerecha(new Nodolistparam(tipo.toString(), ident.toString() ) );
							RESULT=listp;
						}else{
							RESULT=new Nodolistparam(tipo.toString(), ident.toString());
						}
      
              CUP$parser$result = parser.getSymbolFactory().newSymbol("defpar_list",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // decl_funct ::= type ID LPAREN defpar_list RPAREN mainbody 
            {
              NodoBase RESULT =null;
		int tipoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int tiporight = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		NodoBase tipo = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int identleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int identright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Object ident = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int listaleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int listaright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		NodoBase lista = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int cuerpoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cuerporight = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase cuerpo = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 System.out.println("\t Entró a decl_funct --> type ID LPAREN defpar_list RPAREN mainbody"); 
RESULT= new NodoFuncion(ident.toString(),tipo.toString(),lista,cuerpo );     

  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("decl_funct",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // decl_functs ::= EMPTY 
            {
              NodoBase RESULT =null;
		 System.out.println("\t Entró a");  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("decl_functs",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // decl_functs ::= decl_functs decl_funct 
            {
              NodoBase RESULT =null;
		int declaraleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int declararight = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		NodoBase declara = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int dfuncleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int dfuncright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase dfunc = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 System.out.println("\t Entró a decl_functs --> decl_functs decl_funct");

				NodoBase hijoActual = declara;
						if(hijoActual !=null){
							while(hijoActual.TieneHermano()){
								hijoActual = hijoActual.getHermanoDerecha();
							}
							hijoActual.setHermanoDerecha(dfunc);
							RESULT=declara;
						}else{
							RESULT=dfunc;
						}
                   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("decl_functs",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // block ::= mainbody 
            {
              NodoBase RESULT =null;
		int cuerpoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cuerporight = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase cuerpo = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 System.out.println("\t Entró a bloque --> mainbody");	
               RESULT=cuerpo;
             
              CUP$parser$result = parser.getSymbolFactory().newSymbol("block",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // block ::= decl_functs mainbody 
            {
              NodoBase RESULT =null;
		int declararfunleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int declararfunright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		NodoBase declararfun = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int cuerpoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cuerporight = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase cuerpo = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 System.out.println("\t Entró a bloque --> decl_functs mainbody"); 
                RESULT = new NodoBloque(declararfun,cuerpo);     
              CUP$parser$result = parser.getSymbolFactory().newSymbol("block",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // program ::= block 
            {
              Object RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoBase s = (NodoBase)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(modoDepuracion) System.out.println("\t Entró a program --> stmt_seq"); 
					ast = s;
					
              CUP$parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

