
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 20 18:58:19 VET 2015
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OVER = 25;
  public static final int GE = 21;
  public static final int EMPTY = 35;
  public static final int LPAREN = 29;
  public static final int SEMI = 33;
  public static final int REPEAT = 7;
  public static final int INT = 13;
  public static final int FOR = 11;
  public static final int MINUS = 23;
  public static final int WRITE = 10;
  public static final int RPAREN = 30;
  public static final int AND = 27;
  public static final int LT = 18;
  public static final int OR = 28;
  public static final int COMMA = 34;
  public static final int BEGIN = 5;
  public static final int UNTIL = 8;
  public static final int NUM = 36;
  public static final int DIFFERENT = 26;
  public static final int PLUS = 22;
  public static final int ASSIGN = 16;
  public static final int IF = 2;
  public static final int ID = 37;
  public static final int LE = 20;
  public static final int EOF = 0;
  public static final int BOOLEAN = 14;
  public static final int RETURN = 15;
  public static final int TRUE = 38;
  public static final int error = 1;
  public static final int VOID = 12;
  public static final int EQ = 17;
  public static final int LCLASP = 31;
  public static final int TIMES = 24;
  public static final int ELSE = 4;
  public static final int RCLASP = 32;
  public static final int READ = 9;
  public static final int THEN = 3;
  public static final int END = 6;
  public static final int FALSE = 39;
  public static final int GT = 19;
}

